### adding new user

POST http://localhost:5000/addNewUser
Content-Type: application/json

{
    "userName":"Andrius",
    "age":31,
    "email":"Andrius@gausdesimt.com",
    "password":"blahblah",
    "password2":"blahblah"
}

### getting all users

GET http://localhost:5000/allUsers